export default {
    extends: ['stylelint-config-standard-scss'],
    rules: {
        'at-rule-empty-line-before': [
            'always',
            {
                except: ['first-nested'],
                ignore: ['after-comment', 'blockless-after-blockless', 'blockless-after-same-name-blockless'],
                ignoreAtRules: ['else'],
            },
        ],
        'at-rule-no-vendor-prefix': true,
        'block-no-empty': true,
        'color-hex-length': null,
        'color-named': 'never',
        'color-no-invalid-hex': true,
        'comment-empty-line-before': [
            'always',
            {
                except: ['first-nested'],
                ignore: ['stylelint-commands'],
            },
        ],
        'comment-no-empty': true,
        'comment-whitespace-inside': 'always',
        'custom-property-empty-line-before': 'never',
        'declaration-block-no-duplicate-properties': true,
        'declaration-block-no-redundant-longhand-properties': null,
        'declaration-empty-line-before': 'never',
        'font-family-name-quotes': 'always-where-recommended',
        'font-family-no-duplicate-names': true,
        'font-family-no-missing-generic-family-keyword': true,
        'function-calc-no-unspaced-operator': true,
        'function-linear-gradient-no-nonstandard-direction': true,
        'function-name-case': 'lower',
        'function-url-quotes': 'always',
        'function-url-scheme-disallowed-list': 'ftp',
        'keyframe-declaration-no-important': true,
        'keyframes-name-pattern': '',
        'length-zero-no-unit': true,
        'media-feature-name-no-unknown': true,
        'media-feature-name-no-vendor-prefix': true,
        'nesting-selector-no-missing-scoping-root': null,
        'no-descending-specificity': null,
        'no-duplicate-at-import-rules': true,
        'no-duplicate-selectors': true,
        'no-empty-source': true,
        'number-max-precision': 4,
        'property-no-unknown': true,
        'property-no-vendor-prefix': true,
        'rule-empty-line-before': [
            'always',
            {
                ignore: ['after-comment', 'first-nested'],
            },
        ],
        'scss/at-if-no-null': null,
        'scss/at-mixin-argumentless-call-parentheses': null,
        'scss/at-rule-conditional-no-parentheses': null,
        'scss/dollar-variable-empty-line-before': null,
        'scss/dollar-variable-pattern': null,
        'scss/double-slash-comment-empty-line-before': null,
        'scss/no-global-function-names': null,
        'selector-class-pattern': null,
        'selector-max-id': 1,
        'selector-max-pseudo-class': null,
        'selector-no-qualifying-type': null,
        'selector-pseudo-class-no-unknown': true,
        'selector-pseudo-element-colon-notation': 'double',
        'selector-pseudo-element-no-unknown': true,
        'selector-type-no-unknown': [
            true,
            {
                ignore: 'custom-elements',
            },
        ],
        'shorthand-property-no-redundant-values': true,
        'string-no-newline': true,
        'unit-disallowed-list': 'pt',
        'unit-no-unknown': true,
        'value-keyword-case': [
            'lower',
            {
                camelCaseSvgKeywords: true,
            },
        ],
        'value-no-vendor-prefix': true,
        // Ids come from the PHP form builders, and JavaScript and Twig select on them.
        'selector-id-pattern': null,
        // The extended Bootstrap and Inspinia classes live in vendored themes with no placeholders.
        'scss/at-extend-no-missing-placeholder': null,
    },
};
