import { join } from 'node:path';
import { existsSync } from 'node:fs';
import { readConfigurationFile } from '../typescript/configuration-file.mts';
import { resolveBuildConfigurationLocation } from '../typescript/typescript-configuration.mts';

export const getAliasList = (context: string): Record<string, string> => {
    const { filePath: configurationPath, directory } = resolveBuildConfigurationLocation(context);

    if (!existsSync(configurationPath)) {
        throw new Error(
            `The generated Back Office TypeScript configuration ${configurationPath} is missing, so the ` +
                `builder cannot derive its module aliases and every "ZedGuiModules/…" import would fail ` +
                `to resolve.\n` +
                `It is generated by the root "postinstall" script; run "npm run update:config -w spryker-zed-gui" and ` +
                `build again.\n`,
        );
    }

    const configuration = readConfigurationFile(configurationPath);
    const pathAliases = configuration?.compilerOptions?.paths ?? {};
    const aliasList: Record<string, string> = {};

    for (const [aliasName, aliasValues] of Object.entries(pathAliases)) {
        // Aliasing `*` to `*` would make webpack resolve every request through itself.
        if (aliasName === '*' || aliasValues.length === 0) {
            continue;
        }

        const alias = aliasName.replace(/\/\*$/, '');
        const aliasTarget = aliasValues[0].replace(/\/\*$/, '');

        aliasList[alias] = join(context, directory, aliasTarget);
    }

    aliasList.jQuery = 'jquery';

    return aliasList;
};
